name: freewata
favicon: null
layout_spectrum: 0.5973298281896859
typography_spectrum: 0.014177727978676558
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.19391073216684163
  lightness: 0.2974768227431923
  saturation: 0.7250739859882742
  rhythmicContrast: 0.23477065423503518
purpose: []
