name: freewata
favicon: null
layout_spectrum: 0.75648
typography_spectrum: 0.32692
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.125
  lightness: 0
  saturation: 0.3125
  rhythmicContrast: 1
purpose: []
